replicaCount: 1

image: 
  repository: temelkarabacak/go-web-app
  tag: 10121789565
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - paths: /
          pathType: Prefix
